CREATE TABLE CREATURE(
  id               BIGINT         NOT NULL,
  hp     NUMBER         NOT NULL,
  dps     NUMBER         NOT NULL,
  name       VARCHAR(255)      NOT NULL,
  race       VARCHAR(255)        NOT NULL,
  level         NUMBER    NOT NULL
);

ALTER TABLE CREATURE
  ADD CONSTRAINT CREATURE_ID_PK PRIMARY KEY (id);

-- CREATE SEQUENCE SEQ_GAME_RESULT
--   MINVALUE 1
--   MAXVALUE 9223372036854775807
--   START WITH 1
--   INCREMENT BY 1
--   NOCACHE NOCYCLE;